[phases.setup]
packages = ["python3", "gcc"]

[phases.install]
command = """
python -m venv --copies /opt/venv
. /opt/venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
"""

[phases.start]
command = ". /opt/venv/bin/activate && python bot.py"
